### ISSUE TITLE
Should "Neural optimizer search" be counted as a kind of NAS XD?

### ISSUE THREAD

**Issue by hubert0527** [markdtw/awesome-architecture-search#2]
Neural Optimizer Search with Reinforcement Learning
[https://arxiv.org/abs/1709.07417](https://arxiv.org/abs/1709.07417)

**Comment by markdtw** [comment]
NAS = Neural Architecture Search -> search for "architectures"
Neural Optimizer Search = NOS -> search for "optimizer"

it's using search techniques to find better optimizer, not good architectures, so I don't think this should be on the list. It's indeed an interesting paper tho.

If you're interested in using search techniques to find other "deep learning components", they also have a paper about searching for activation function [here](https://arxiv.org/abs/1710.05941)
